export function profileView({data,escape,safeUrl}) {
  const icons={
    email:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',
    github:'<path d="M9 19c-4 1-4-2-6-2m12 5v-4a3.5 3.5 0 0 0-1-2.7c3.3-.4 6.7-1.6 6.7-7.3a5.7 5.7 0 0 0-1.5-4c.2-1 .2-2-.2-3-1.5-.4-3.3.8-4.2 1.4a14 14 0 0 0-7.6 0C6.3 1.8 4.5.6 3 1c-.4 1-.4 2-.2 3a5.7 5.7 0 0 0-1.5 4c0 5.7 3.4 6.9 6.7 7.3A3.5 3.5 0 0 0 7 18v4" transform="translate(1 0) scale(.94)"/>',
    blog:'<path d="M12 5c-3-2-6-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1Zm0 0v15"/>',
    scholar:'<path d="m2 8 10-5 10 5-10 5L2 8Zm4 2v6c3 3 9 3 12 0v-6m4-2v8"/>',
    wechat:'<path d="M13.5 13.8c-1 .5-2.2.8-3.5.8-.9 0-1.8-.1-2.6-.4L4 16l.8-3A5.2 5.2 0 0 1 2 8.5C2 5.5 5.4 3 9.5 3c3.9 0 7.1 2.2 7.5 5"/><path d="M22 14c0 1.6-.8 3-2.2 3.9l.6 2.5-2.9-1.4c-.7.2-1.4.3-2.1.3-3.6 0-6.4-2.3-6.4-5.3s2.8-5.3 6.4-5.3S22 11 22 14Z"/><g fill="currentColor" stroke="none"><circle cx="7" cy="7.7" r=".8"/><circle cx="12" cy="7.7" r=".8"/><circle cx="13" cy="13.2" r=".8"/><circle cx="17.5" cy="13.2" r=".8"/></g>',
    moon:'<path d="M20 14.5A8.3 8.3 0 0 1 9.5 4a8.4 8.4 0 1 0 10.5 10.5Z"/>',
    sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>'
  };
  const icon=name=>`<svg viewBox="0 0 24 24" width="21" height="21" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${icons[name]}</svg>`;
  const nav=[['about','About'],...[
    ['news','News'],['education','Education'],['publications','Publications'],
    ['awards','Awards'],['service','Service'],['projects','Projects']
  ].filter(([key])=>data[key]?.length)];
  const section=(id,title,body)=>data[id]?.length?`<section id="${id}"><h2>${title}</h2>${body}</section>`:'';
  const date=value=>value?`<span class="date">${escape(value)}</span>`:'';
  const authors=items=>items.map(author=>`${author.name===data.name?`<strong>${escape(author.name)}</strong>`:escape(author.name)}${author.equal?'<sup aria-label="equal contribution">*</sup>':''}`).join(', ');
  const news=section('news','News',`<ul class="news-list">${(data.news||[]).map(item=>`<li><time${item.datetime?` datetime="${escape(item.datetime)}"`:''}>${escape(item.date)}</time><span>${escape(item.text)}${item.target?` <a href="#${escape(item.target)}" aria-label="Read the publication details">Publication details</a>`:''}${item.url?` <a href="${safeUrl(item.url)}">${escape(item.linkLabel||'Project')}</a>`:''}</span></li>`).join('')}</ul>`);
  const education=section('education','Education',(data.education||[]).map(item=>`<article class="education-entry"><div class="entry-title"><h3>${escape(item.institution)}</h3>${date(item.dates)}</div><p>${escape(item.degree)}</p>${item.detail?`<p class="secondary">${escape(item.detail)}</p>`:''}${item.additional?`<p class="secondary">${escape(item.additional)}</p>`:''}</article>`).join(''));
  const publications=section('publications','Publications',`<p class="contribution-note">* Equal contribution.</p>${(data.publications||[]).map(item=>`<article class="publication-entry" id="${escape(item.id)}"><h3>${escape(item.title)}</h3><p class="publication-authors">${authors(item.authors)}</p><p class="publication-venue${item.status==='under-review'?' under-review':''}">${escape(item.venue)}</p>${item.description?`<p class="publication-description">${escape(item.description)}</p>`:''}${item.links?.length?`<nav class="publication-links" aria-label="Links for ${escape(item.title)}">${item.links.map(link=>`<a href="${safeUrl(link.url)}">${escape(link.label)}</a>`).join(' ')}</nav>`:''}</article>`).join('')}`);
  const awards=section('awards','Awards',`<ul class="awards-list">${(data.awards||[]).map(item=>`<li><div><span>${escape(item.title)}</span>${item.detail?`<span class="award-detail">${escape(item.detail)}</span>`:''}</div>${date(item.date)}</li>`).join('')}</ul>`);
  const service=section('service','Service',(data.service||[]).map(item=>`<article class="service-entry"><div class="entry-title"><h3>${escape(item.title)}</h3>${date(item.dates)}</div><p class="secondary">${escape(item.organization)}</p>${item.description?`<p>${escape(item.description)}</p>`:''}</article>`).join(''));
  const projects=section('projects','Projects',(data.projects||[]).map(item=>`<article class="project-entry"><div class="entry-title"><h3>${item.url?`<a href="${safeUrl(item.url)}">${escape(item.title)}</a>`:escape(item.title)}</h3>${date(item.dates)}</div><p>${escape(item.description)}</p>${item.label?`<p class="secondary project-tools">${escape(item.label)}</p>`:''}</article>`).join(''));
  return `<header class="site-header"><div class="navigation"><nav aria-label="Page sections">${nav.map(([id,label],i)=>`<a href="#${id}" ${i===0?'aria-current="location"':''}>${label}</a>`).join('')}<a href="${safeUrl(data.blog)}">Blog</a></nav><button class="theme-button" type="button" aria-label="Switch to dark theme" title="Switch to dark theme" hidden><span class="moon">${icon('moon')}</span><span class="sun">${icon('sun')}</span></button></div></header>
  <div class="profile-layout"><aside class="profile-sidebar" aria-label="Personal profile"><div class="profile-card"><img class="profile-portrait" src="avatar.jpg" alt="Quan’s rabbit avatar" width="208" height="208"><div class="profile-details"><h1>${escape(data.name)} <span lang="zh-CN">(${escape(data.chineseName)})</span></h1><p class="profile-role">${escape(data.role)}</p><p class="profile-affiliation">${escape(data.affiliation)}</p><nav class="profile-contacts" aria-label="Contact and other sites"><a href="mailto:${escape(data.email)}" aria-label="Email Quan Chen" title="${escape(data.email)}">${icon('email')}</a><a href="${safeUrl(data.github)}" aria-label="GitHub" title="GitHub">${icon('github')}</a><a href="${safeUrl(data.blog)}" aria-label="Blog" title="Blog">${icon('blog')}</a>${data.scholar?`<a class="scholar-link" href="${safeUrl(data.scholar)}" aria-label="Google Scholar" title="Google Scholar">${icon('scholar')}</a>`:''}${data.wechatId?`<details class="wechat-contact"><summary aria-label="WeChat" title="WeChat">${icon('wechat')}</summary><div class="wechat-info"><strong>WeChat ID:</strong> <span>${escape(data.wechatId)}</span></div></details>`:''}${data.cv?`<a href="${safeUrl(data.cv)}">CV</a>`:''}</nav></div></div></aside>
  <main class="profile-main" id="main" tabindex="-1"><section id="about"><h2>About</h2>${data.intro.map(text=>`<p>${escape(text)}</p>`).join('')}</section>
  ${news}${education}${publications}${awards}${service}${projects}
  <footer><span>${escape(data.name)} <span lang="zh-CN">${escape(data.chineseName)}</span></span><a href="#about">Back to top</a></footer></main></div>`;
}
